module.exports = {
    blockchain: {
        network: 'http://localhost:8545',
        start_block: 403,
        launch_timestamp: '1619489201',
    },
    trigger_scheduler: {
        pending_transaction_check: '5 * * * * *',
        bot_balance_check: '10 * * * * *',
        invest: '3 * * * * *',
        harvest: '13 * * * * *',
        pnl: '23 * * * * *',
        rebalance: '33 * * * * *',
        generate_stats: '10 * * * * *',
        bot_curve_check: '53 * * * * *',
        deposit_withdraw_event: '30 * * * * *',
    },
    emoji: {
        regularBot: ':control_knobs:',
        criticalBot: ':ambulance:',
        statsBot: ':control_knobs:',
        error: ':x:',
        gvt: ':high_brightness:',
        pwrd: ':low_brightness:',
        miniStatsPersonal: ':bar_chart:',
        stats: ':bar_chart:',
        depositEvent: ':chart_with_upwards_trend:',
        withdrawEvent: ':chart_with_downwards_trend:',
        transferEvent: ':arrow_right:',
        reverted: ':warning:',
        investTrigger: ':inbox_tray:',
        curveInvestTrigger: ':inbox_tray:',
        invest: ':inbox_tray:',
        curveInvest: ':inbox_tray:',
        harvestTrigger: ':hammer_pick:',
        harvest: ':hammer_pick:',
        pnlTrigger: ':moneybag:',
        pnl: ':moneybag:',
        rebalanceTrigger: ':scales:',
        rebalance: ':scales:',
    },
    stats_folder: '../stats',
    log_folder: './logs',
    blockNumberFile: './lastBlockNumber.json',
    stats_latest: '../stats/gro-latest.json',
    vault_name: ['DAI yVault', 'USDC yVault', 'USDT yVault', '3CRV yVault'],
    stable_coin: ['DAI', 'USDC', 'USDT'],
    protocol: ['Harvest', 'Cream', 'Curve'],
    strategy_name: ['Harvest', 'Cream'],
    lifeguard_name: '3CRV',
    contracts: {
        controller: '0xFC628dd79137395F3C9744e33b1c5DE554D94882',
    },
    discord: {
        token: process.env[`DISCORD_TOKEN_${process.env.BOT_ENV}`],
        retry: 3,
        channel: {
            trades: '825998630828638239',
            protocol_assets: '825998746696810536',
            protocol_events: '825998886249168896',
            crit_action_events: '825998966691987456',
            bot_alerts: '825999025487609927',
            bot_logs: '825999075971039283',
        },
    },
};
