-- Data migration from `gro` into `g2`

INSERT INTO g2."EV_AIRDROP_CLAIMS" SELECT * FROM gro."EV_AIRDROP_CLAIMS";
INSERT INTO g2."EV_APPROVALS" SELECT * FROM gro."EV_APPROVALS";
INSERT INTO g2."EV_GRO_DEPOSITS" SELECT * FROM gro."EV_GRO_DEPOSITS";
INSERT INTO g2."EV_GRO_EMERGENCY_WITHDRAWALS" SELECT * FROM gro."EV_GRO_EMERGENCY_WITHDRAWALS";
INSERT INTO g2."EV_GRO_PNL_EXECUTION" SELECT * FROM gro."EV_GRO_PNL_EXECUTION";
INSERT INTO g2."EV_GRO_STRATEGY_HARVEST" SELECT * FROM gro."EV_GRO_STRATEGY_HARVEST";
INSERT INTO g2."EV_GRO_STRATEGY_UPDATE_RATIO" SELECT * FROM gro."EV_GRO_STRATEGY_UPDATE_RATIO";
INSERT INTO g2."EV_GRO_WITHDRAWALS" SELECT * FROM gro."EV_GRO_WITHDRAWALS";
INSERT INTO g2."EV_HODLER_CLAIMS" SELECT * FROM gro."EV_HODLER_CLAIMS";
INSERT INTO g2."EV_LAB_AH_LATEST_STRATEGY" SELECT * FROM gro."EV_LAB_AH_LATEST_STRATEGY";
INSERT INTO g2."EV_LAB_AH_POSITIONS" SELECT * FROM gro."EV_LAB_AH_POSITIONS";
INSERT INTO g2."EV_LAB_AH_POSITION_ADJUSTED" SELECT * FROM gro."EV_LAB_AH_POSITION_ADJUSTED";
INSERT INTO g2."EV_LAB_AH_POSITION_CLOSED" SELECT * FROM gro."EV_LAB_AH_POSITION_CLOSED";
INSERT INTO g2."EV_LAB_AH_POSITION_OPENED" SELECT * FROM gro."EV_LAB_AH_POSITION_OPENED";
INSERT INTO g2."EV_LAB_CLAIMS" SELECT * FROM gro."EV_LAB_CLAIMS";
INSERT INTO g2."EV_LAB_DEPOSITS" SELECT * FROM gro."EV_LAB_DEPOSITS";
INSERT INTO g2."EV_LAB_DROPS" SELECT * FROM gro."EV_LAB_DROPS";
INSERT INTO g2."EV_LAB_NEW_RELEASE_FACTOR" SELECT * FROM gro."EV_LAB_NEW_RELEASE_FACTOR";
INSERT INTO g2."EV_LAB_STRATEGY_HARVEST" SELECT * FROM gro."EV_LAB_STRATEGY_HARVEST";
INSERT INTO g2."EV_LAB_VAULT_HARVEST" SELECT * FROM gro."EV_LAB_VAULT_HARVEST";
INSERT INTO g2."EV_LAB_WITHDRAWALS" SELECT * FROM gro."EV_LAB_WITHDRAWALS";
INSERT INTO g2."EV_POOL_BAL_LIQUIDITY" SELECT * FROM gro."EV_POOL_BAL_LIQUIDITY";
INSERT INTO g2."EV_POOL_BAL_SWAP" SELECT * FROM gro."EV_POOL_BAL_SWAP";
INSERT INTO g2."EV_POOL_META_LIQUIDITY" SELECT * FROM gro."EV_POOL_META_LIQUIDITY";
INSERT INTO g2."EV_POOL_META_SWAP" SELECT * FROM gro."EV_POOL_META_SWAP";
INSERT INTO g2."EV_POOL_UNI_LIQUIDITY" SELECT * FROM gro."EV_POOL_UNI_LIQUIDITY";
INSERT INTO g2."EV_POOL_UNI_SWAP" SELECT * FROM gro."EV_POOL_UNI_SWAP";
--INSERT INTO g2."EV_PRICE" SELECT * FROM gro."EV_PRICE";  -- Required, but to be filtered (no need to insert all data, but recent one)
INSERT INTO g2."EV_STAKER_ADD_POOL" SELECT * FROM gro."EV_STAKER_ADD_POOL";
INSERT INTO g2."EV_STAKER_CLAIMS" SELECT * FROM gro."EV_STAKER_CLAIMS";
INSERT INTO g2."EV_STAKER_DEPOSITS" SELECT * FROM gro."EV_STAKER_DEPOSITS";
INSERT INTO g2."EV_STAKER_GRO_PER_BLOCK" SELECT * FROM gro."EV_STAKER_GRO_PER_BLOCK";
INSERT INTO g2."EV_STAKER_MAX_GRO_PER_BLOCK" SELECT * FROM gro."EV_STAKER_MAX_GRO_PER_BLOCK";
INSERT INTO g2."EV_STAKER_SET_POOL" SELECT * FROM gro."EV_STAKER_SET_POOL";
INSERT INTO g2."EV_STAKER_UPDATE_POOL" SELECT * FROM gro."EV_STAKER_UPDATE_POOL";
INSERT INTO g2."EV_STAKER_USERS_MIGRATED" SELECT * FROM gro."EV_STAKER_USERS_MIGRATED";
INSERT INTO g2."EV_STAKER_WITHDRAWALS" SELECT * FROM gro."EV_STAKER_WITHDRAWALS";
INSERT INTO g2."EV_STRATEGY_REPORTED" SELECT * FROM gro."EV_STRATEGY_REPORTED";
--INSERT INTO g2."EV_TOKEN_PRICES" SELECT * FROM gro."EV_TOKEN_PRICES";  -- Perhaps not required
INSERT INTO g2."EV_TRANSACTIONS" SELECT * FROM gro."EV_TRANSACTIONS";
--ON CONFLICT ON CONSTRAINT "EV_TRANSACTIONS_pkey" DO NOTHING;
INSERT INTO g2."EV_VESTING_EXITS" SELECT * FROM gro."EV_VESTING_EXITS";
INSERT INTO g2."EV_VESTING_EXTENSIONS" SELECT * FROM gro."EV_VESTING_EXTENSIONS";
INSERT INTO g2."EV_VESTING_MAX_LOCK_PERIOD" SELECT * FROM gro."EV_VESTING_MAX_LOCK_PERIOD";
INSERT INTO g2."EV_VESTING_VESTS" SELECT * FROM gro."EV_VESTING_VESTS";
INSERT INTO g2."PROTOCOL_APY" SELECT * FROM gro."PROTOCOL_APY";
INSERT INTO g2."EV_TRANSFERS" (
    transaction_id,
    log_index,
    contract_address,
    block_timestamp,
    log_name,
    token_id,
    "from",
    "to",
    "value",
    factor,
    creation_date
)
 select
    transaction_id,
    log_index,
    contract_address,
    block_timestamp,
    log_name,
    token_id,
    "from",
    "to",
    "value",
    factor,
    creation_date
 from gro."EV_TRANSFERS";
--ON CONFLICT ON CONSTRAINT "EV_TRANSFERS_pkey" DO NOTHING;

-- Data migration from `g2_internal` into `g2` [only for testing]
/*
INSERT INTO g2."EV_G2_CONVEX_STRATEGY_HARVEST" SELECT * FROM g2_internal."EV_G2_CONVEX_STRATEGY_HARVEST";
INSERT INTO g2."EV_G2_NEW_PNL" SELECT * FROM g2_internal."EV_G2_NEW_PNL";
INSERT INTO g2."EV_G2_PNL_FIXED_RATED_DISTRIBUTION" SELECT * FROM g2_internal."EV_G2_PNL_FIXED_RATED_DISTRIBUTION";
INSERT INTO g2."EV_G2_ROUTER_DEPOSITS" SELECT * FROM g2_internal."EV_G2_ROUTER_DEPOSITS";
INSERT INTO g2."EV_G2_ROUTER_WITHDRAWALS" SELECT * FROM g2_internal."EV_G2_ROUTER_WITHDRAWALS";
INSERT INTO g2."EV_G2_TRANCHE_BALANCES" SELECT * FROM g2_internal."EV_G2_TRANCHE_BALANCES";
INSERT INTO g2."EV_G2_TRANCHE_DEPOSITS" SELECT * FROM g2_internal."EV_G2_TRANCHE_DEPOSITS";
INSERT INTO g2."EV_G2_TRANCHE_WITHDRAWALS" SELECT * FROM g2_internal."EV_G2_TRANCHE_WITHDRAWALS";
INSERT INTO g2."EV_G2_VAULT_DEPOSITS" SELECT * FROM g2_internal."EV_G2_VAULT_DEPOSITS";
INSERT INTO g2."EV_G2_VAULT_RELEASE_FACTOR" SELECT * FROM g2_internal."EV_G2_VAULT_RELEASE_FACTOR";
INSERT INTO g2."EV_G2_VAULT_STRATEGY_CHANGES" SELECT * FROM g2_internal."EV_G2_VAULT_STRATEGY_CHANGES";
INSERT INTO g2."EV_G2_VAULT_STRATEGY_HARVEST" SELECT * FROM g2_internal."EV_G2_VAULT_STRATEGY_HARVEST";
INSERT INTO g2."EV_G2_VAULT_STRATEGY_QUEUE" SELECT * FROM g2_internal."EV_G2_VAULT_STRATEGY_QUEUE";
INSERT INTO g2."EV_G2_VAULT_STRATEGY_WITHDRAWALS" SELECT * FROM g2_internal."EV_G2_VAULT_STRATEGY_WITHDRAWALS";
INSERT INTO g2."EV_G2_VAULT_WITHDRAWALS" SELECT * FROM g2_internal."EV_G2_VAULT_WITHDRAWALS";
*/
