INSERT INTO gro."EV_GRO_WITHDRAWALS" (
        "transaction_id",
        "log_index",
        "contract_address",
        "block_timestamp",
        "log_name",
        "token_id",
        "user",
        "referral",
        "balanced",
        "all",
        "deduct_usd",
        "return_usd",
        "lp_amount",
        "amount1",
        "amount2",
        "amount3"
    )
VALUES (
        $1,
        $2,
        $3,
        $4,
        $5,
        $6,
        $7,
        $8,
        $9,
        $10,
        $11,
        $12,
        $13,
        $14,
        $15,
        $16
    ) ON CONFLICT ON CONSTRAINT "EV_GRO_WITHDRAWALS_pkey" DO NOTHING;