INSERT INTO gro."USER_STD_FACT_TRANSFERS" (
        "block_number",
        "block_timestamp",
        "transfer_date",
        "tx_hash",
        "network_id",
        "transfer_type",
        "user_address",
        "referral_address",
        "usd_value",
        "gvt_value",
        "pwrd_value",
        "gvt_amount",
        "pwrd_amount",
        "usd_deduct",
        "usd_return",
        "lp_amount",
        "stable_amount",
        "dai_amount",
        "usdc_amount",
        "usdt_amount",
        "gro_amount",
        "creation_date"
    )
SELECT d."block_number",
    b."block_timestamp",
    to_timestamp(b.block_timestamp)::timestamp,
    d."tx_hash",
    d."network_id",
    d."transfer_type",
    d."user_address",
    d."referral_address",
    sum(d."usd_value"),
    sum(d."gvt_value"),
    sum(d."pwrd_value"),
    sum(d."gvt_amount"),
    sum(d."pwrd_amount"),
    0,
    0,
    0,
    sum(d."stable_amount"),
    sum(d."dai_amount"),
    sum(d."usdc_amount"),
    sum(d."usdt_amount"),
    sum(d."gro_amount"),
    now()
FROM gro."USER_STD_TMP_DEPOSITS" d
    LEFT JOIN gro."ETH_BLOCKS" b ON d.block_number = b.block_number
    GROUP BY
    d."block_number",
    b."block_timestamp",
    to_timestamp(b.block_timestamp)::timestamp,
    d."tx_hash",
    d."network_id",
    d."transfer_type",
    d."user_address",
    d."referral_address",
    now()
UNION ALL
SELECT w."block_number",
    b."block_timestamp",
    to_timestamp(b.block_timestamp)::timestamp,
    w."tx_hash",
    w."network_id",
    w."transfer_type",
    w."user_address",
    w."referral_address",
    sum(w."usd_value"),
    sum(w."gvt_value"),
    sum(w."pwrd_value"),
    sum(w."gvt_amount"),
    sum(w."pwrd_amount"),
    sum(w."usd_deduct"),
    sum(w."usd_return"),
    sum(w."lp_amount"),
    sum(w."stable_amount"),
    sum(w."dai_amount"),
    sum(w."usdc_amount"),
    sum(w."usdt_amount"),
    sum(w."gro_amount"),
    now()
FROM gro."USER_STD_TMP_WITHDRAWALS" w
    LEFT JOIN gro."ETH_BLOCKS" b ON w.block_number = b.block_number
    GROUP BY
    w."block_number",
    b."block_timestamp",
    to_timestamp(b.block_timestamp)::timestamp,
    w."tx_hash",
    w."network_id",
    w."transfer_type",
    w."user_address",
    w."referral_address",
    now();
    