INSERT INTO gro."TMP_USER_DEPOSITS" (
        "block_number",
        "tx_hash",
        "network_id",
        "user_address",
        "referral_address",
        "usd_value",
        "gvt_value",
        "pwrd_value",
        "usd_amount",
        "gvt_amount",
        "pwrd_amount",
        "dai_amount",
        "usdc_amount",
        "usdt_amount",
        "creation_date"
    )
VALUES (
        $1,
        $2,
        $3,
        $4,
        $5,
        $6,
        $7,
        $8,
        $9,
        $10,
        $11,
        $12,
        $13,
        $14,
        $15
    );